version: "3"
services:
  spring_BE:
    image: jaehyeon1114/spring:latest
    restart: always
    ports:
      - 8081:8080
    environment: #localhost로 깔끼면 안 됨
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/toy_project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toy_project
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    ports:
      - 3309:3306
    networks:
      - my-network
networks:
  my-network: